services:
  - type: web
    name: choose-you
    runtime: ruby
    buildCommand: bundle install && npm ci && npm run build:production && bundle exec rails assets:precompile
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    env: ruby-3.2.9
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: choose-you-redis

  - type: redis
    name: choose-you-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
