development:
  adapter: async

test:
  adapter: test

production:
  # REDIS_URLが利用可能ならredis、そうでなければasync
  adapter: <%= ENV['REDIS_URL'].present? ? 'redis' : 'async' %>
  <% if ENV['REDIS_URL'].present? %>
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: choose_you_production
  <% end %>
